-- Derby-ready starter schema for portfolio documentation/demo extension.
-- This project runs immediately with an in-memory AppStore, so Derby setup is optional.
CREATE TABLE USERS (
    USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR(120),
    EMAIL VARCHAR(120) UNIQUE,
    PASSWORD VARCHAR(120),
    ROLE_NAME VARCHAR(40),
    STUDENT_OR_STAFF_NUMBER VARCHAR(50),
    PHONE VARCHAR(40)
);

CREATE TABLE SERVICE_REQUESTS (
    REQUEST_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(160),
    DESCRIPTION VARCHAR(2000),
    CATEGORY_NAME VARCHAR(120),
    DEPARTMENT_NAME VARCHAR(120),
    CREATED_BY_EMAIL VARCHAR(120),
    PRIORITY VARCHAR(30),
    STATUS VARCHAR(30),
    CREATED_AT TIMESTAMP
);
